/*
 * Copyright (c) 2020. Gary Becks - <techstar.dev@hotmail.com>
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { MutationMethod, isQueryMethod, QueryMethod } from '@typerpc/schema'

export const capitalize = (text: string): string => text.replace(/^\w/, (c) => c.toUpperCase())

export const lowerCase = (text: string): string => text.replace(/^\w/, (c) => c.toLowerCase())

export const currentTime = () => {
    const now = new Date()
    return `${now.getFullYear()}/${now.getMonth()}/${now.getDate()} at ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`
}

export const fileHeader = () => `
// ****************************************************
// CODE GENERATED BY TYPERPC ON ${currentTime()}
// TO REPORT A BUG, REQUEST A NEW FEATURE, OR OTHER
// ISSUES, VISIT https://github.com/typerpc/cli/issues
// ****************************************************
\n`

// returns the correct content-type for a server response
export const serverResponseContentType = (method: MutationMethod | QueryMethod) =>
    method.hasCborReturn ? "'application/cbor'" : "'application/json'"

// returns the correct content-type for a client request
export const clientRequestContentType = (method: MutationMethod | QueryMethod) =>
    isQueryMethod(method) ? '' : method.hasCborParams ? "'application/cbor'" : "'application/json'"
