import {MutationMethod} from '../schema'

export const capitalize = (text: string): string => text.replace(/^\w/, c => c.toUpperCase())

export const lowerCase = (text: string): string => text.replace(/^\w/, c => c.toLowerCase())

export const currentTime = () => {
  const now = new Date()
  return `${now.getFullYear()}/${now.getMonth()}/${now.getDate()} at ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`
}

export const fileHeader = () => `
// ****************************************************
// CODE GENERATED BY TYPERPC ON ${currentTime()}
// EDITING GENERATED CODE BY HAND IS HIGHLY DISCOURAGED,
// EDITING SCHEMAS AND REGENERATING CODE IS PREFERRED.
// TO REPORT A BUG, REQUEST A NEW FEATURE, OR OTHER
// ISSUES, VISIT https://github.com/g5becks/typeRPC/issues
// ****************************************************
\n`

// returns the correct content-type for a server response
export const serverResponseContentType = (method: MutationMethod) => method.hasCborReturn ? 'application/cbor' : 'application/json'

// returns the correct content-type for a client request
export const clientRequestContentType = (method: MutationMethod) => method.hasCborParams ? 'application/cbor' : 'application/json'
