import {RpcService} from './pyy6kw6ods6vi0gy7yqys'

// ****************************************************
// CODE GENERATED BY TYPERPC ON 2020/6/24 at 14:47:50
// EDITING GENERATED CODE BY HAND IS HIGHLY DISCOURAGED,
// EDITING SCHEMAS AND REGENERATING CODE IS PREFERRED.
// TO REPORT A BUG, REQUEST A NEW FEATURE, OR OTHER
// ISSUES, VISIT https://github.com/g5becks/typeRPC/issues
// ****************************************************

export type Person = {
  age: number;
  name: string;
  interests: string[];
}

export type GetPersonByNameRequest = {
  name: string;

}

export type GetPeopleResponse = {
  data: Person[];
}

export type GetPersonByNameResponse = {
  data: Person;
}

export interface PersonService extends RpcService {
  getPeople(): Promise<Person[]>;
  getPersonByName(name: string): Promise<Person>;
}
